In [1]:
import numpy as np

In [2]:
n = 5
i = 4
o = 3

In [38]:
arr = np.array([[1.],[2.],[3.]])
out = 1./(1+np.exp(-arr))
print(out)
print(out.shape,arr.shape)

[[0.73105858]
 [0.88079708]
 [0.95257413]]
(3, 1) (3, 1)


In [39]:
mask = np.multiply(out,1-out)
print(mask)
dD = np.mean(mask,axis=0)
print(dD)

[[0.19661193]
 [0.10499359]
 [0.04517666]]
[0.11559406]


In [40]:
arr = np.array([[1.,2.,3.,8.],[4.,5.,6.,7.],[9.,10.,11.,12.]])
exp_arr = np.exp(arr)
out = exp_arr/(np.sum(exp_arr,axis=1).reshape(-1,1))
print(out)
print(arr.shape,out.shape)

[[9.02738505e-04 2.45389767e-03 6.67038546e-03 9.89972978e-01]
 [3.20586033e-02 8.71443187e-02 2.36882818e-01 6.43914260e-01]
 [3.20586033e-02 8.71443187e-02 2.36882818e-01 6.43914260e-01]]
(3, 4) (3, 4)


In [41]:
dU = np.array([1.,2.,3.,4.])

In [42]:
mask = np.multiply(out,1-out)
print(mask)
dD = np.mean(mask,axis=0)
print(dD)
print(np.multiply(dU,dD))

[[0.00090192 0.00244788 0.00662589 0.00992648]
 [0.03103085 0.07955019 0.18076935 0.22928869]
 [0.03103085 0.07955019 0.18076935 0.22928869]]
[0.02098787 0.05384942 0.12272153 0.15616795]
[0.02098787 0.10769883 0.36816459 0.6246718 ]


In [50]:
arr = [[1.,1.,-0.1,0.1],[0.1,-0.1,-0.2,1]]
out = np.maximum(arr,0)
print(out)
mask = (out > 0).astype(np.float64)
print(mask)
dD = np.multiply(dU,np.mean(mask,axis=0))
print(dD)

[[1.  1.  0.  0.1]
 [0.1 0.  0.  1. ]]
[[1. 1. 0. 1.]
 [1. 0. 0. 1.]]
[1. 1. 0. 4.]


In [3]:
X = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
print(X.shape)

(5, 4)


In [4]:
W = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(W.shape)

(4, 3)


In [5]:
b = np.array([1,2,3])
print(b.shape)

(3,)


In [6]:
print(W.dot(b))

[14 32 50 68]


In [7]:
%%time
out = np.empty_like(W)
for row in X:
    b = b.reshape(-1,1)
    row = row.reshape(-1,1)
    out += np.dot(row,b.T)
print(out)

[[-9223372036854775763  8070459316572356053  3180211159507796109]
 [ 2466321565078348884  3257281401135968406  3617298904385859785]
 [ 4121976961963733105  7311068618032822687  2466321603649696791]
 [ 3828686942337445489 -2305834224891695209     1697634184685933]]
CPU times: user 954 µs, sys: 631 µs, total: 1.59 ms
Wall time: 1.64 ms


In [8]:
b=b.reshape(-1,)

In [9]:
b.shape

(3,)

In [10]:
row.shape

(4, 1)

In [11]:
row.T

array([[17, 18, 19, 20]])

In [12]:
%load_ext autoreload
%autoreload 2

In [13]:
y_true = np.array([1,0,0,1])
y_pred = np.array([0.9,0.1,0.8,0.2])
loss = np.sum(-np.multiply(y_true,np.log(y_pred))-np.multiply((1-y_true),np.log(1-y_pred)))
print(loss)

3.4295968561838537


In [14]:
grad = -np.divide(y_true,y_pred)+np.divide(1-y_true,1-y_pred)
print(grad)

[-1.11111111  1.11111111  5.         -5.        ]


In [15]:
1*grad

array([-1.11111111,  1.11111111,  5.        , -5.        ])

In [22]:
import pandas as pd
df = pd.read_csv('diabetes.csv')
df = np.array(df)
y = df[:,-1]
X = df[:,:-1]

In [23]:
X = (X-X.mean())/(X.std())

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [47]:
from models.sequential import Sequential
from layers.fc import *
m = Sequential(loss='bce')
m.add_layer(FC(in_dim=X.shape[1],out_dim=10))
m.add_layer(FC(10,10))
m.add_layer(FC(10,10))
m.add_layer(FC(10,1,activation='sigmoid'))
m.describe()

-----------------------------------
FC Layer			90
-----------------------------------
FC Layer			110
-----------------------------------
FC Layer			110
-----------------------------------
FC Layer			11
-----------------------------------
Total Parameters		321
-----------------------------------



In [46]:
m.train(X_train,y_train,lr=6e-3,epochs=1_000,debug=100)

Loss: 400.3270, 1/1000
Loss: 400.3590, 100/1000
Loss: 400.2548, 200/1000
Loss: 398.9319, 300/1000
Loss: 396.8958, 400/1000
Loss: 419.9317, 500/1000
Loss: 818.9896, 600/1000
Loss: 426.5454, 700/1000
Loss: 396.5545, 800/1000


/Users/sukruthkartheek/smol/losses/bce_loss.py:13: RuntimeWarning: invalid value encountered in log
  loss = np.sum(-np.multiply(self.y_true,np.log(self.y_pred))-np.multiply((1-self.y_true),np.log(1-self.y_pred)))


Loss: nan, 900/1000
Loss: nan, 1000/1000


In [38]:
m.train(X_train,y_train,lr=1e-3,epochs=1_000,debug=100)

Loss: 539.5412, 1/1000
Loss: 539.2731, 100/1000
Loss: 539.2366, 200/1000
Loss: 539.4456, 300/1000
Loss: 539.9165, 400/1000
Loss: 540.6690, 500/1000
Loss: 541.9237, 600/1000
Loss: 544.2309, 700/1000
Loss: 547.1606, 800/1000
Loss: 550.8260, 900/1000
Loss: 555.7020, 1000/1000


In [ ]:
m.train(X_train,y_train,lr=1e-3,epochs=1_000,debug=100)

In [34]:
preds = m.forward(X_test)
preds_bin = (preds>=0.5).astype(int)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,preds_bin))

[[101   0]
 [ 53   0]]
